package server

var startCommas = ",,,,,,,,,,,,,"
var endCommas = ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,"
var nameMap = map[string]string{
	"austen.abro":      "18,Austin Abro" + startCommas,
	"james":            "95,James Allen" + startCommas,
	"jase":             "82,Jase Koonce" + startCommas,
	"gedd":             "7,Gedd Johnson" + startCommas,
	"brieshepherd":     "127,Brie Shepherd" + startCommas,
	"andrew.blanchard": "9,Andrew Blanchard" + startCommas,
	"anthony":          "13,Anthony Wendt" + startCommas,
	"rob.mengert":      "49,Rob Mengert" + startCommas,
	"marc":             "129,Marc Ray" + startCommas,
	"jacob.may":        "114,Jacob May" + startCommas,
	"lauren":           "62,Lauren Mengert" + startCommas,
	"bridget":          "27,Bridget Regan" + startCommas,
	"phillip":          "58,Phillip Record" + startCommas,
	"audrey":           "78,Audrey Ettesvold" + startCommas,
	"josh":             "19,Joshua Oates" + startCommas,
	"jade.mims":        "30,Jade Mims" + startCommas,
	"wayne":            "37,Wayne Starr" + startCommas,
	"sigridschneider":  "115,Sigrid Schneider" + startCommas,
	"caseywylie":       "125,Casey Wylie" + startCommas,
	"gato.harvey":      "51,Gato Harvey" + startCommas,
	"megan":            "22,Megan Wolf" + startCommas,
	"rob":              "38,Robert Slaughter" + startCommas,
	"kinseyparham":     "141,Kinsey Parham" + startCommas,
	"cnpartain":        "34,Courtney Partain" + startCommas,
	"jhardin":          "79,Jessica Hardin" + startCommas,
	"carly":            "65,Carly Charbonnet" + startCommas,
	"gregoryhorvath":   "123,Gregory Horvath" + startCommas,
	"sam.k":            "68,Sam Kreimier" + startCommas,
	"andrew":           "28,Andrew Greene" + startCommas,
	"jon":              "42,Jonathan Perry" + startCommas,
	"gabe":             "8,Gabriel Scarberry" + startCommas,
	"micah.nagel":      "57,Micah Nagel" + startCommas,
	"chris":            "92,Chris Harden" + startCommas,
	"jonfandrew":       "72,Jon Andrew" + startCommas,
	"madeline":         "46,Madeline Fortner" + startCommas,
	"mike.vanhemert":   "36,Mikael Vanhemert" + startCommas,
	"joshuabrewer":     "100,Joshua Brewer" + startCommas,
	"noah":             "134,Noah Birrer" + startCommas,
}
